### ISSUE TITLE
Clicked on New Conversation button gives 404 route error.

### ISSUE THREAD

**Issue by develpertarun** [musonza/chat-demo#12]
After pulling the master branch and then run the command the php artisan serve. Interface gets loaded successfully but when click on New Conversation button it is giving 404 error.

http://127.0.0.1:8000/conversations
Route does not exist in web.php file.
![Screen Shot 2019-11-09 at 12 09 14 PM](https://user-images.githubusercontent.com/7922508/68524209-e45a9a80-02e9-11ea-869c-df76b85f6ef9.png)

Could you please guide what next to do to rectify this issue?

Thanks

**Comment by kefivitch** [comment]
I notice that if you are getting the conversation by id and it doesn't exist on the database then 404 not found will be shown

**Comment by musonza** [comment]
The package comes with the routes https://github.com/musonza/chat/blob/master/src/Http/routes.php Check your prefix in config file
