### ISSUE TITLE
Demo currently in broken state

### ISSUE THREAD

**Issue by hennell-git** [musonza/chat-demo#13]
Liked the look of the chat package, so checked out this demo app, but it's current status is not usable.

Running migrations gives a 
````
Symfony\Component\Debug\Exception\FatalErrorException  :
Cannot declare class CreateChatTables, because the name is already in use at
/chat-demo/database/migrations/2019_11_06_134235_create_chat_tables.php:104
````
Seems this is because there's two migration files currently in the repo:
**2019_10_31_015755_create_chat_tables.php** & **2019_11_06_134235_create_chat_tables.php**

Removing one makes stuff work, but only briefly, loging in you can't start a new conversation as /routes 404's (see #12 )

Brief look through the history and reverting to commit #bdc8748 seemed to solve many of these issues - and while it might not be the latest and greatest way of using the package, it does let me see what the package does out of the box!

I appreciate what you're trying to do here, and love having a demo app to examine how packages are used, but wonder if having a more defined develop branch you can work on to showcase all features and a slower (tested 100% working branch) for people who just want to try it out and see if they like the look of it before diving deeper?

**Comment by carlituxman** [comment]
Please solve this. I want test it

Thanks!

**Comment by aayaresko** [comment]
I confirm, the demo is broken

**Comment by musonza** [comment]
Please try now

**Comment by mdhafizur** [comment]
It's still not working

**Comment by musonza** [comment]
@mdhafizur what's the error?

**Comment by musonza** [comment]
@hennell-git i will create a branch for the previous version. Thanks

**Comment by mdhafizur** [comment]
> 
> 
> @hennell-git i will create a branch for the previous version. Thanks

Have you uploaded it yet?

**Comment by carlituxman** [comment]
I just change some lines at ChatConversations.vue and working.
methods: createConversation and leaveConversation

**Comment by mdhafizur** [comment]
What changes did you make? @carlituxman

**Comment by carlituxman** [comment]
> What changes did you make? @carlituxman

at createConversation add /chat to route , but leaveConversation not working, I need get te participation id but I'm looking how. 

Can anyone help me how?

**Comment by AlifAbhiesa** [comment]
is still not working?

**Comment by carlituxman** [comment]
> is still not working?

fail joinConversation and leaveConversation with 404

**Comment by musonza** [comment]
The url with the 404, does it have this prefix https://github.com/musonza/chat-demo/blob/17a0e634fcbf25fd7c9f4da9323c2c9b9348a9e9/config/musonza_chat.php#L41 ?

**Comment by carlituxman** [comment]
But the vue component not.

The leaveConversation fail because need participation id like second parameter.

How can obtain this id?

**Comment by AlifAbhiesa** [comment]
> #bdc8748

That version isn’t showing us realtime chat

**Comment by AlifAbhiesa** [comment]
> The url with the 404, does it have this prefix
> 
> https://github.com/musonza/chat-demo/blob/17a0e634fcbf25fd7c9f4da9323c2c9b9348a9e9/config/musonza_chat.php#L41
> 
> ? Also what version of the package is in your composer.lock file

No, it’s happen because there’s no routing for /conversation on routing/web.php
Hope you fix it

**Comment by musonza** [comment]
@AlifAbhiesa i just fixed it. Check now
<img width="1143" alt="chat-screen" src="https://user-images.githubusercontent.com/3452388/69681142-253d0800-107b-11ea-8a93-0aa5946a1020.png">

**Comment by carlituxman** [comment]
> @AlifAbhiesa i just fixed it. Check now
> <img alt="chat-screen" width="1143" src="https://user-images.githubusercontent.com/3452388/69681142-253d0800-107b-11ea-8a93-0aa5946a1020.png">

But leaveConvesation is 404 still

**Comment by mdhafizur** [comment]
it would be great if you fix it asap as i have been waiting for the fix for few days and my project deadline is very near. Thank You @musonza

**Comment by carlituxman** [comment]
if know how obtain the participation id is easy to fix

can help us?

**Comment by musonza** [comment]
This should work for the demo to get participation_id
https://github.com/musonza/chat-demo/blob/69d80d0c1ae8b4fa459f153180080899ebe4a781/resources/js/components/ChatConversations.vue#L71-L73

**Comment by carlituxman** [comment]
working!!
