### ISSUE TITLE
if it in broken state why u not remove the demo!!

### ISSUE THREAD

**Issue by MOHAMMED-ABD-RAZAQ** [musonza/chat-demo#14]
i had spent one hour download the demo then it broken!!!
man!!

**Comment by musonza** [comment]
What is broken? You didn't give anything that can help address it. Also the code even with bugs it helps other people getting started. I did however update the package and tested and it's working fine

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
where can i find routes of api of converstions and there bro

**Comment by MOHAMMED-ABD-RAZAQ** [comment]
![image](https://user-images.githubusercontent.com/29556066/69423310-d3247b80-0d36-11ea-9729-5e398bb8750f.png)
i searched about the links i cant find thim

**Comment by musonza** [comment]
I fixed the issue https://github.com/musonza/chat-demo/blob/0ad3de47fa0f2b3b4887d1a88926e5b1342fea0a/resources/js/components/ChatConversations.vue#L51
The routes are in the package here https://github.com/musonza/chat/blob/master/src/Http/routes.php
