### ISSUE TITLE
Issue with pusher

### ISSUE THREAD

**Issue by mdhafizur** [musonza/chat-demo#15]
Hi Musonza,

Tried to implement pusher with the project.
Though pusher detects message passing. but it's not real-time in the app.
Any idea how to fix it?

**Comment by musonza** [comment]
You have to uncomment this line https://github.com/musonza/chat-demo/blob/50afc2dc21a0a16b66cc0b3cf37f9c68b144af2d/resources/js/components/ChatMessages.vue#L60

Comment this out 
https://github.com/musonza/chat-demo/blob/50afc2dc21a0a16b66cc0b3cf37f9c68b144af2d/resources/js/components/ChatForm.vue#L55

I will add instructions to README when i get a chance

**Comment by horaceho** [comment]
I follow the above instruction https://github.com/horaceho/chat-demo/commit/0e99f41c5fef792d905506feffe0d5243c12bfb6 and re-run the demo. 

Pusher is connected:

![Screen 2020-02-14 at 10 52 18](https://user-images.githubusercontent.com/6657/74497432-a1c3e200-4f18-11ea-9a58-aa0b3e490ae8.png)

However, new message only shows up after manual refresh page (pressing Cmd-R, 1 & 2 are shown), the new message (e.g. enter 3 and click Send) does not show up in own window:

![Screen 2020-02-14 at 10 54 01](https://user-images.githubusercontent.com/6657/74497952-fddb3600-4f19-11ea-8ffd-86387e079c0b.png)

or remote window:

![Screen 2020-02-14 at 10 54 03](https://user-images.githubusercontent.com/6657/74497962-0895cb00-4f1a-11ea-96f1-eb0f71039e1e.png)

Any suggestion?

**Comment by musonza** [comment]
I need to update readme
You need to comment this out https://github.com/musonza/chat-demo/blob/5985fea7b19a4c5f20f86fbc8502798e9ae9508a/resources/js/components/ChatForm.vue#L55
https://github.com/musonza/chat-demo/blob/5985fea7b19a4c5f20f86fbc8502798e9ae9508a/resources/js/components/ChatMessages.vue#L60

**Comment by horaceho** [comment]
> I need to update readme
> You need to comment this out
> 
> https://github.com/musonza/chat-demo/blob/5985fea7b19a4c5f20f86fbc8502798e9ae9508a/resources/js/components/ChatForm.vue#L55
> 
> 
> Remove this comment
> https://github.com/musonza/chat-demo/blob/5985fea7b19a4c5f20f86fbc8502798e9ae9508a/resources/js/components/ChatMessages.vue#L60

I've done that, please see my fork: https://github.com/horaceho/chat-demo/commit/0e99f41c5fef792d905506feffe0d5243c12bfb6
