### ISSUE TITLE
Semantic Errors. when joining the chat

### ISSUE THREAD

**Issue by mdhafizur** [musonza/chat-demo#16]
HTTP422: UNPROCESSABLE ENTITY - The request was well-formed but could not be processed due to semantic errors. (XHR)POST - http://127.0.0.1:8000/chat/conversations/17/participants
```
`joinConversation: function joinConversation(id) {
            var payload = {
                'participants': [{
                    'id': window.participant && window.participant.id,
                    'type': window.participant && window.participant.type
                }]
            };

            axios.post("/chat/conversations/" + id + "/participants", payload).then(function (response) {
                window.location.href = "chat?conversation_id=" + id;
            });`
```
The controller is same. As i faced it few people said i need to pass the right value . I did everything right.
But still can't figure out what is causing it.
I would really appreciate the help.
Thanks

**Comment by musonza** [comment]
@mdhafizur can you check the exact error message in the logs? Also what do you get from console.log `window.participant` ?  I see you are checking if `window.participant && window.participant.type` type is set or is set. If not you get `undefined` so you have to handle that somewhere

**Comment by mdhafizur** [comment]
This is what i got from network mode->body
{"message":"The given data was invalid.","errors":{"participants.0.id":["The participants.0.id field is required."],"participants.0.type":["The participants.0.type field is required."]}}

And from console.log
HTTP422: UNPROCESSABLE ENTITY - The request was well-formed but could not be processed due to semantic errors.
(XHR)POST - http://127.0.0.1:8000/chat/conversations/1/participants

and for 
 'participants': [{
                    'id': window.participant.id,
                    'type':  window.participant.type
                }]
            };
Unable to get property 'id' of undefined or null reference

**Comment by mdhafizur** [comment]
Hey Musonza
Hope not to bother you.
How can i solve the problem?
I have only 3 days to complete the project.

**Comment by musonza** [comment]
hey add me on Discord  `tinashe#3295`
