### ISSUE TITLE
first user created does not see any conversations / can't create conversations

### ISSUE THREAD

**Issue by rawrkats** [musonza/chat-demo#2]
Testing out the demo and discovered this issue. 
![Screenshot from 2019-08-20 07-38-39](https://user-images.githubusercontent.com/398227/63357097-be8eac80-c31d-11e9-9c9b-5dd12832b24d.png)

i logged out and logged back in to see if perhaps there was a session issue or something. No avail.

Great work by the way!

**Comment by musonza** [comment]
i can't reproduce this issue. Working fine for me. Did you get it working?

**Comment by rawrkats** [comment]
not yet, I have been reading your source code to get real familiar with the setup so I could provide some more info. I will do another install later today, will keep you updated on it. Perhaps just a one-off.
